run:
  timeout: 5m
linters-settings:
  govet:
    enable-all: true
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - misspell
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-use-default: true
