project_name: deepl-cli

release:
  github:
    owner: candy12t
    name: deepl-cli
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/deepl-cli
    binary: bin/deepl-cli
    ldflags:
      -s -w -X github.com/candy12t/deepl-cli/internal/build.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: macOS
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
