// Code generated by MockGen. DO NOT EDIT.
// Source: deepl.go

// Package mock_webapi is a generated GoMock package.
package mock_webapi

import (
	reflect "reflect"

	entity "github.com/candy12t/deepl-cli/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockDeepL is a mock of DeepL interface.
type MockDeepL struct {
	ctrl     *gomock.Controller
	recorder *MockDeepLMockRecorder
}

// MockDeepLMockRecorder is the mock recorder for MockDeepL.
type MockDeepLMockRecorder struct {
	mock *MockDeepL
}

// NewMockDeepL creates a new mock instance.
func NewMockDeepL(ctrl *gomock.Controller) *MockDeepL {
	mock := &MockDeepL{ctrl: ctrl}
	mock.recorder = &MockDeepLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeepL) EXPECT() *MockDeepLMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockDeepL) Translate(arg0 *entity.Translation) (*entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(*entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockDeepLMockRecorder) Translate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockDeepL)(nil).Translate), arg0)
}
