name: CI
on: [push, pull_request]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Download dependencies
        run: go mod download

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: Run tests
        run: make test

      - name: Build
        run: make build
